# Generated by Django 3.1.13 on 2021-10-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0004_initial_part_4'),
        ('nautobot_device_lifecycle_mgmt', '0003_service_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatedsoftwarelcm',
            name='device_types',
            field=models.ManyToManyField(blank=True, related_name='_validatedsoftwarelcm_device_types_+', to='dcim.DeviceType'),
        ),
        migrations.AddField(
            model_name='validatedsoftwarelcm',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='_validatedsoftwarelcm_devices_+', to='dcim.Device'),
        ),
        migrations.AddField(
            model_name='validatedsoftwarelcm',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, related_name='_validatedsoftwarelcm_inventory_items_+', to='dcim.InventoryItem'),
        ),
        migrations.AddField(
            model_name='validatedsoftwarelcm',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='_validatedsoftwarelcm_roles_+', to='dcim.DeviceRole'),
        ),
        migrations.AlterUniqueTogether(
            name='validatedsoftwarelcm',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='validatedsoftwarelcm',
            name='assigned_to_content_type',
        ),
        migrations.RemoveField(
            model_name='validatedsoftwarelcm',
            name='assigned_to_object_id',
        ),
    ]
